stages:
  - compile

variables:
  PROJECT_NAME: algorithmia-scala
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  RUNNING_ON_BUILD_SERVER: "true"

compile:compile:
  stage: compile
  image: algorithmiahq/sbt-builder:11.0.6_1.3.8_2.13.1
  script:
  - sbt compile
